defaults:
  - base  # 公共基础配置
  - _self_       # 当前阶段特有配置

debug: false
enable_cuda_optimizations: true
use_wandb: false
use_deepspeed_plugin: true
fold: 0
task:
  name: semi                     # 当前运行的任务名称: qcot, semi, hard 之一


dataset:
  negative_dataset: ../input/negatives_semi.csv
  negative_cot_dataset: ../input/negatives_cot.csv

model:
  use_lora: true
  init_type: fp32  # bf16,fp16

train_params:
  retriever_bs: 128 #memory ~ bs * num_negative or bs(if negative_dataset ==0)
  sub_batch_size: 8 # emebding memory
  query_bs: 128 # evaluate
  content_bs: 128 # evaluate 128/8=16

  num_negative: 8
  num_cot_negative: 8
  warmup_pct: 0.16 # 0.15-->0.05或0.08  
  num_epochs: 15 # 10-->30  
  grad_accumulation_steps: 1 # if want 128, 128/retriever_bs
  patience: 3
  eval_at_start: false

  loss:
    alpha: 0.4  
    beta:  0.2  # 强化Q-CoT对齐  
    gamma:  0.4 # 强化R-CoT对齐

optimizer:
  name: AdamW
  head_keywords: headmodel
  
  lr:  1.2e-5
  lr_lora_a:  1.5e-5
  lr_lora_b: 2e-5
  lr_embed_tokens: 2e-5
  lr_head: 2e-5 

  max_grad_norm: 0.5
  adam_beta_1: 0.9
  adam_beta_2: 0.95
  adam_epsilon: 1e-8
  weight_decay: 1e-2
# 前10%训练步：max_grad_norm=0.5（严格稳定）

# 中间50%训练步：max_grad_norm=1.0（平衡）

# 后40%训练步：max_grad_norm=2.0（加速收敛）
