defaults:
  - base  # 公共基础配置
  - _self_       # 当前阶段特有配置

debug: false
enable_cuda_optimizations: true
use_wandb: false
fold: 0
task: hard

dataset:
  negative_dataset: ../input/negatives_hard.csv

model:
  backbone_path: ../models/eedi_embed_bge_abl_semi
  

train_params:
  retriever_bs: 16 #memory ~ bs * num_negative or bs(if negative_dataset ==0)
  sub_batch_size: 4 # emebding memory
  query_bs: 128 # evaluate
  content_bs: 128 # evaluate 128/8=16

  num_negative: 8
  warmup_pct: 0.1
  num_epochs: 10
  grad_accumulation_steps: 8 # if want 128, 128/retriever_bs
  patience: 20
  eval_at_start: false

  loss:
    alpha: 1 # 只保留TripletLoss
    beta: 0
    gamma: 0

optimizer:
  name: AdamW
  head_keywords: head
  
  lr:  1e-5
  lr_lora_a:  1e-5
  lr_lora_b: 5e-5
  lr_embed_tokens: 8e-5
  lr_head: 3e-4 

  max_grad_norm: 1
  adam_beta_1: 0.9
  adam_beta_2: 0.95
  adam_epsilon: 1e-8
  weight_decay: 1e-2
# 前10%训练步：max_grad_norm=0.5（严格稳定）

# 中间50%训练步：max_grad_norm=1.0（平衡）

# 后40%训练步：max_grad_norm=2.0（加速收敛）
outputs:
  model_dir: ../models/eedi_embed_bge_abl_hard